In [1]:
import pandas as pd
import csv
from tqdm import tqdm_notebook as tqdm

In [3]:
fields = ["C1", "C2", "C3"]
df_train = pd.read_csv("/home/emil/CTRP/train.csv", sep=";", nrows=100)

In [4]:
df_train.head(100)

,timestamp,label,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,CG1,CG2,CG3,l1,l2,C11,C12
0,1379278800,0,2733540231,3500392421,4454,15573,11,995,2,176,15,671,"384,382,96,88,185,49,385,268,448,438,279,420,1...",NaN,NaN,32,0,0,106
1,1379278800,0,1964843810,1232327635,2081,2547,11,995,2,361,15,802,"96,49,385,268,107,438,418,124,357,17,435,130,3...",NaN,NaN,1,0,0,106
2,1379278800,0,660357674,2066571765,602,29581,29,995,0,468,15,758,"170,169,205,204,176,252,243,382,98,220,222,181...",NaN,NaN,119,0,0,103
3,1379278800,0,2962648192,2373358995,4018,36969,30,995,2,8,15,67,"273,205,383,382,381,219,216,215,225,49,47,54,3...","28071,6916,9108",NaN,0,0,0,106
4,1379278800,0,1822613420,446973819,2081,23457,35,995,0,452,15,821,"268,419,357,18,331,59,57,99,154,155,76,412,122...",NaN,NaN,5,0,0,106
5,1379278800,0,2230694362,462046911,4781,16144,6,1694,0,390,22,822,"273,184,180,49,54,269,100,270,419,80,83,74,5,3...",NaN,"43845,45509,45500,15529,33701,49513,49517,3834...",3,0,1,105
6,1379278800,0,149405498,2008468818,5454,24226,11,995,0,313,15,821,"273,205,176,247,249,252,384,382,375,93,88,188,...",NaN,NaN,0,0,0,105
7,1379278800,0,1651740157,929846473,5678,4314,10,995,2,419,15,24,"273,170,169,205,173,176,246,213,252,243,380,38...","18587,21441,22177",NaN,26,0,0,104
8,1379278800,0,1207866034,1976462420,3353,4241,88,995,2,177,15,5,"88,215,53,269,417,1,17,239,331,60,57,306,277,9...","14566,12599",NaN,52,0,0,106
9,1379278800,0,2132391877,3482861549,3595,6952,83,995,2,419,15,479,"273,169,205,250,384,95,96,215,185,184,49,47,53...","423,19225,5001",NaN,0,0,0,105
10,1379278800,0,1207866034,1095451340,2360,33431,88,995,2,177,15,5,"88,215,53,269,417,1,17,239,331,60,57,306,277,9...","14566,12599",NaN,42,0,0,106
11,1379278800,0,1822613420,2277192293,2081,21050,35,995,0,452,15,821,"268,419,357,18,331,59,57,99,154,155,76,412,122...",NaN,NaN,0,0,0,106
12,1379278800,0,4192834470,3674600013,5704,422,1,1694,2,390,22,49,"242,383,381,96,216,188,49,385,448,103,438,419,...",NaN,"8894,8894,75,33701,49517,38344,56597,27922,468...",2,0,1,104
13,1379278800,0,1895538078,4123103882,2360,33431,88,995,2,177,15,48,"243,377,384,269,46,138,437,279,280,420,161,74,...",NaN,NaN,12,0,0,105
14,1379278800,0,1822613420,2840661346,1590,4057,30,995,0,452,15,821,"268,419,357,18,331,59,57,99,154,155,76,412,122...",NaN,NaN,3,0,0,106
15,1379278800,0,3404707152,3500392421,4454,15573,11,995,2,176,15,251,"216,449,123,3,18,330,59,57,149,99,154,155,76,4...",NaN,NaN,41,0,0,105
16,1379278800,0,3829649523,1232327635,2081,2547,11,995,2,361,15,802,"103,418,236,14,343,341,435,130,331,59,58,99,15...",NaN,NaN,7,0,0,106
17,1379278800,0,1895538078,4283011642,3353,17918,88,995,2,177,15,48,"243,377,384,269,46,138,437,279,280,420,161,74,...",NaN,NaN,13,0,0,105
18,1379278800,0,3242443620,3570349185,109,13832,0,3905,2,147,53,49,"273,205,242,93,95,96,88,186,189,188,184,181,49...",28107,46594,1,0,1,103
19,1379278800,0,3367776458,2366864073,4943,736,31,995,0,248,15,1387,"50,53,449,106,279,420,161,74,123,364,231,18,23...",11782,NaN,27,0,0,105
20,1379278800,0,3120997466,1695423685,5318,7157,11,995,2,361,15,1306,"246,250,216,422,437,103,280,420,124,376,3,18,3...",NaN,NaN,8,0,0,106
21,1379278800,0,2263499518,1314736296,465,6603,52,995,2,452,15,821,"170,169,205,174,173,246,247,249,380,377,383,38...",2894,NaN,0,0,0,106
22,1379278800,0,1992197611,3649618909,3952,25033,11,995,2,176,15,491,"448,104,239,277,276,99,154,155,76,412,139,333,...",NaN,NaN,1,0,0,104
23,1379278800,0,2662484318,3747633635,3542,19246,6,551,2,362,20,313,"268,422,419,124,1,17,431,343,341,435,130,331,5...","1964,3282",NaN,7,0,1,104
24,1379278800,0,3367776458,4116346656,2360,16554,31,995,0,248,15,1387,"50,53,449,106,279,420,161,74,123,364,231,18,23...",11782,NaN,20,0,0,105
25,1379278800,0,2263499518,402681528,2081,17110,52,995,2,452,15,821,"170,169,205,174,173,246,247,249,380,377,383,38...",2894,NaN,0,0,0,106
26,1379278800,0,154126019,1232327635,2081,2547,11,995,2,361,15,802,"377,383,216,215,49,54,269,448,270,419,0,236,13...",NaN,NaN,21,0,0,106
27,1379278800,0,2263499518,2064356622,393,23166,52,995,2,452,15,821,"170,169,205,174,173,246,247,249,380,377,383,38...",2894,NaN,14,0,0,106
28,1379278800,0,2636489958,1931060789,5728,31367,19,995,2,419,15,490,"340,176,184,51,422,251,3,236,409,59,58,265,151...",NaN,NaN,5,0,0,106
29,1379278800,0,3967702140,3747633635,3542,19246,6,995,2,365,1,548,"377,382,381,96,216,215,181,48,269,46,416,422,4...",NaN,"55412,45509,33701,49513,49518,54846,38346,5659...",0,0,0,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,1379278801,0,139804378,2573758929,2252,7718,74,995,0,419,15,672,"176,245,95,96,88,49,449,107,123,4,5,356,235,23...",26901,NaN,2,0,0,103
71,1379278801,0,2558523350,166012999,6098,12141,10,995,2,419,15,1306,"273,169,204,174,176,380,97,96,216,183,50,53,33...",NaN,NaN,0,0,0,106
72,1379278801,0,1609534524,3126403322,4866,25359,83,995,2,419,15,802,"273,169,176,250,242,380,379,377,384,382,381,96...",NaN,NaN,1,0,0,105
73,1379278801,0,1422191203,4256006179,3018,15480,25,2230,2,390,43,738,"170,169,205,174,382,52,55,386,448,107,123,208,...",NaN,"43841,45509,75,33701,56597,59585,59832,15387,4...",0,0,1,106
74,1379278801,0,3462409646,3345814630,5765,30132,1,2880,0,390,47,821,"47,54,269,336,416,279,420,14,331,58,65,277,276...","17627,19745,15172,6623,2890","2464,45509,49272,38344,59585,46839,55412,51248...",1,0,1,105
75,1379278801,0,3904572886,981283737,2252,33022,31,995,2,8,15,596,"216,124,123,18,331,59,58,444,154,155,76,412,12...",NaN,NaN,52,0,0,106
76,1379278801,0,490571397,1543285064,2458,19317,11,995,2,361,15,29,"242,377,384,383,382,220,222,183,184,47,53,385,...",NaN,NaN,24,0,0,106
77,1379278801,0,3159185823,1021079522,5184,18716,85,995,2,419,15,312,"169,205,174,88,220,188,183,54,385,269,438,418,...",NaN,NaN,1,0,0,104
78,1379278801,0,2168888250,1772979573,5184,4974,52,995,2,452,15,821,"273,176,245,243,380,96,225,186,183,184,181,53,...",NaN,NaN,0,0,0,105
79,1379278801,0,2033730775,1526656913,925,28887,52,1670,0,94,1,1326,"205,174,379,382,220,184,180,49,50,47,53,52,385...",NaN,NaN,25,0,1,105
80,1379278801,0,3341227356,388842707,742,21172,11,995,0,70,15,821,"96,88,222,180,50,47,53,52,416,422,437,100,106,...",NaN,NaN,0,0,0,101
81,1379278801,0,2830446473,266046120,3710,25584,88,995,2,177,15,802,"51,268,422,420,357,230,18,431,343,341,435,202,...",28625,NaN,6,0,0,104
82,1379278801,0,234563512,3662598231,2252,26696,31,995,0,8,15,821,"273,205,377,384,382,91,222,185,181,47,53,54,38...",NaN,NaN,230,0,0,104
83,1379278801,0,731604205,1207044385,3550,26026,87,995,2,282,15,1046,"269,422,418,357,18,331,59,99,154,155,76,412,12...",NaN,NaN,4,0,0,105
84,1379278801,0,2323596083,2598790127,3092,29770,88,995,2,177,15,802,"96,216,184,46,138,422,100,279,280,161,85,74,12...","29595,29595,7636",NaN,1,0,0,106
85,1379278801,0,96605508,1436343506,6317,23127,30,995,0,122,15,816,"220,184,180,50,53,437,124,3,356,409,59,388,395...",NaN,NaN,1,0,0,105
86,1379278801,0,4285990038,1600143803,5548,17249,1,95,2,363,1,413,"170,205,246,88,183,181,53,268,416,422,140,270,...",NaN,NaN,1,0,1,105
87,1379278801,0,2952258890,3929066068,831,1298,99,995,0,39,15,51,"205,181,388,300,301,99,154,155,76,412,122,139,...",17740,NaN,0,0,0,105
88,1379278801,0,860048293,1608376237,6107,29072,0,3905,2,147,44,746,"99,154,155,76,412,122,139,333,332,335,334",NaN,46594,0,0,1,103
89,1379278801,0,731604205,4003379817,4662,24434,4,995,2,361,15,1046,"269,422,418,357,18,331,59,99,154,155,76,412,12...",NaN,NaN,0,0,0,105
90,1379278801,0,2216025591,1520937431,2252,11347,88,995,2,177,15,802,"176,379,382,215,54,269,448,419,3,357,14,130,17...",NaN,NaN,303,0,0,106
91,1379278801,0,3367776458,1898994485,2252,35241,31,995,0,248,15,1387,"50,53,449,106,279,420,161,74,123,364,231,18,23...",11782,NaN,21,0,0,105
92,1379278801,0,3688503904,2541448775,510,1866,10,995,2,419,15,821,"205,204,174,246,247,249,98,96,88,220,224,186,1...",NaN,NaN,0,0,0,105
93,1379278801,0,430475766,2189871098,325,14657,95,3905,0,147,44,49,"205,174,173,246,247,248,249,250,252,379,384,38...","5520,27756,12292,25124,25301,19436,25493,12097...","43844,46594",2,0,1,104
94,1379278801,0,2608315895,2424428473,3806,2039,30,995,0,212,15,239,"204,243,380,379,224,49,52,56,268,422,420,357,1...",NaN,NaN,22,0,0,106
95,1379278801,0,2665787752,523092702,3345,10353,30,995,2,212,15,1297,"246,384,382,49,422,103,279,419,124,236,18,239,...",NaN,NaN,4,0,0,103
96,1379278801,0,1269053990,37423075,2656,7255,30,995,2,428,15,802,"205,380,384,382,98,96,220,222,186,188,183,49,4...",NaN,NaN,46,0,0,106
97,1379278801,0,2531732449,3229139375,6327,19540,0,3403,0,391,28,742,"169,205,204,173,176,246,213,380,379,382,381,96...",NaN,"43844,45501,46594,32632",0,0,1,104
98,1379278801,0,229762405,1855207754,599,4883,92,2770,2,390,47,43,"242,243,88,216,50,53,54,52,56,448,107,74,124,5...","5661,15380","75,75,33701,54846,38344,38346,56597,46839,4383...",9,0,1,104
99,1379278801,0,2033730775,446973819,2081,23457,35,1670,0,94,1,1326,"205,174,379,382,220,184,180,49,50,47,53,52,385...",NaN,NaN,10,0,1,105

In [1]:
with open('/home/emil/CTRP/train_libffm', 'rb') as f, open('/home/emil/CTRP/train_libffm.bin', 'wb') as g: 
    for row in f:
        g.write(row)

## change labels from 0 to -1

In [4]:
with open('/home/emil/CTRP/data/test.csv', newline='') as csvfile, open('/home/emil/CTRP/data/test1.csv', 'w', newline='') as csvout: 
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')       
    spamwriter = csv.writer(csvout, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    row = next(spamreader)
    spamwriter.writerow(row)
    for row in tqdm(spamreader):
        if int(row[1]) == 0:
            row[1] = -1
        spamwriter.writerow(row)

Widget Javascript not detected.  It may not be installed or enabled properly.

## Collide two submissions

In [3]:
with open('/home/emil/Downloads/submission_FFM_20.csv', newline='') as csv_ffm, open('/home/emil/Downloads/submission.csv', newline='') as csv_vw: 
    with open('/home/emil/Downloads/collision.csv', 'w') as wr:
        rdr_ffm = csv.reader(csv_ffm, delimiter=',', quotechar='|')
        rdr_vw = csv.reader(csv_vw, delimiter=',', quotechar='|')
        _ = next(rdr_ffm)
        _ = next(rdr_vw)
        wr.write("Id,Click\n")
        for ffm, vw in zip(rdr_ffm, rdr_vw):
            res = 0.35*float(ffm[1]) + 0.65*float(vw[1])
            wr.write(str(ffm[0]) + "," + str(res) + "\n")

## save for libffm

In [5]:
with open('/home/emil/CTRP/train_drop_groups.csv', newline='') as csvfile, open('/home/emil/CTRP/train_libffm', 'wb') as f: 
    spamreader = csv.reader(csvfile, delimiter=';', quotechar='|')
    hdr = next(spamreader)
    indices = list(map(str, range(0, len(hdr) - 1)))
    for row in spamreader:
        
        out_line = row[1] + " " 
        row = [row[0]] + row[2:]
        zipper = list(zip(indices, row))
        out_line += " ".join([a + ":1:" + b for a,b in zipper[0:1]]) + " "
        out_line += " ".join([a + ":" + b + ":1" for a,b in zipper[1:11]])+ " "
        out_line += " ".join([a + ":1:" + b for a,b in zipper[11:13]])+ " "
        out_line += " ".join([a + ":" + b + ":1" for a,b in zipper[13:]])+ " "
        f.write(str.encode(out_line[:-1] + '\n'))

## Drop groups of categorical

In [2]:
with open('/home/emil/CTRP/train.csv', newline='') as csvfile, open('/home/emil/CTRP/train_drop_groups.csv', 'w', newline='') as csvout: 
    spamreader = csv.reader(csvfile, delimiter=';', quotechar='|')       
    spamwriter = csv.writer(csvout, delimiter=';',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    for row in spamreader:
        out_row = row[0:12]
        out_row.extend(row[15:])
        spamwriter.writerow(out_row)

## Creating VW dataset

In [27]:
hdr

['C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'C9',
 'C10',
 'l1',
 'l2',
 'C11',
 'C12']

In [39]:
with open('/home/emil/CTRP/test_drop_groups.csv', newline='') as csvfile, open('/home/emil/CTRP/test_recent.vw', 'w') as vw:
    spamreader = csv.reader(csvfile, delimiter=';', quotechar='|')       
    hdr = next(spamreader)
    hdr = [hdr[0]] + hdr[2:]
    
    for row in spamreader:
        if int(row[1]) == 0:
            out_line = '-1 '
        else:
            out_line = '1 '
        row = [row[0]] + row[2:]
        zipper = list(zip(hdr, row))
        out_line += '|ts '
        out_line += " ".join([a + ":" + b for a,b in zipper[0:1]])
        out_line += ' |cat1 '
        out_line += " ".join([a + "=" + b for a,b in zipper[1:11]])
        out_line += ' |int1 '
        out_line += " ".join([a + ":" + b for a,b in zipper[11:13]])
        out_line += ' |cat2 '
        out_line += " ".join([a + "=" + b for a,b in zipper[13:]])
        vw.write(out_line[:-1] + '\n')

## Create submission

In [40]:
i = 1
with open("/home/emil/CTRP/preds_recent.txt", "r") as f, open("/home/emil/CTRP/submission2.txt", "w") as g:
    g.write("Id,Click\n")
    for prob in f:
        g.write(str(i)+','+prob)
        i+=1

### Make preprocess of dataset for LIBFFM and VW

In [ ]:
import zlib
from collections import defaultdict

HEADER = "timestamp;label;C1;C2;C3;C4;C5;C6;C7;C8;C9;C10;CG1;CG2;CG3;l1;l2;C11;C12".split(';')
COUNT_BASIC = 2
COUNT_CATEG_FIRST = 10
COUNT_GROUP = 3
COUNT_CATEG_SECOND = 2
COUNT_CATEGORIAL = COUNT_CATEG_FIRST+COUNT_CATEG_SECOND

OUT_HEADER = "timestamp;Label;I1;I2;C1;C2;C3;C4;C5;C6;C7;C8;C9;C10;C11;C12;C13;C14;C15".split(';')


def ProcessGroup(group_name, stat, group_feature):
    if group_feature == '':
        return ''
    for val in group_feature.split(','):
        stat[group_name+"\t"+val] += 1

    return str(zlib.crc32(group_feature.encode()))

def GetFeatures(input_str, global_statistics):
    features = {}
    group_processed = 1
    for feature_id, feature_str in enumerate(input_str.split(';')):
        feature_name = HEADER[feature_id]
        if feature_name == 'label':
            feature_name = 'Label'
        elif feature_name.startswith('CG'): # group
            feature_str = ProcessGroup(feature_name, global_stat, feature_str)
            feature_name = 'C'+str(COUNT_CATEGORIAL + group_processed)
            group_processed += 1
        elif feature_name.startswith('l'): # counters
            feature_name = feature_name.replace('l', 'I')

        features.update({feature_name: feature_str})
        if feature_name.startswith('C'):
            global_statistics[feature_name+"-"+feature_str] += 1

    return features

def CreateOutFeatures(input_str, statistics):
    features = GetFeatures(input_str, statistics)
    out = ""
    for feature_name in OUT_HEADER:
        feature_val = features.get(feature_name)
        if feature_val is None:
            feature_val = ''
        out += feature_val + ","
    return out[:-1]

def ProcessFile(filename_in, filename_out, global_statistics):
    with open(filename_in, 'r', encoding='utf-8') as input, \
            open(filename_out, 'w', encoding='utf-8') as output:
        output.write(','.join(OUT_HEADER)+'\n')
        for counter, line in enumerate(input):
            if line.startswith('timestamp'):
                continue

            line = line[:-1]
            out_line = CreateOutFeatures(line, global_statistics)
            output.write(out_line+'\n')
            if counter % 100000 == 0:
                print(filename_in, counter)

global_stat = defaultdict(int)
ProcessFile('data/train.csv', 'data/train', global_stat)
ProcessFile('data/test.csv', 'data/test', global_stat)

sorted_stat = sorted(global_stat.items(), key=lambda kv: -kv[1])
with open('data/stat_1.txt', 'w', encoding='utf-8') as stat_file:
    for stat_name, stat_count in sorted_stat:
        stat_file.write(stat_name+"\t"+str(stat_count)+"\n")